server:
  port: 8080
spring:
  application:
    name: petTheGarden
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true   #false로 할 경우 Hot Deployment 기능을 비활성화하여 서버가 자동으로 재시작되지 않도록 설정
  lifecycle:
    timeout-per-shutdown-phase: 30s  # 서버 종료 시 세션이 30초 내에 종료되도록 설정
  datasource:
    hikari:
      maximum-pool-size: 5  # 최대 연결 풀 크기 (동시에 열 수 있는 연결의 최대 수)
      minimum-idle: 2   # 최소 유휴 연결 수 (유휴 상태로 남을 수 있는 최소 연결 수)
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@hgx0hi4cecqm3yyb_high?TNS_ADMIN=C:/wallet
    username: pet
    password: Garden12345678
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
logging:
  level:
    root: info
    org:
      hibernate:
        sql: debug

file:
  path: C:/PTGUpload/